---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yongzyzhang.
--- DateTime: 2024/5/18 下午6:06
---

---@class ClientContext
---@field GetStatus function
local ClientContext = {}

---@class IRPCStatus
---@field OK function RPC调用是否成功
---@field GetFrameworkRetCode function 框架错误吗
---@field GetFuncRetCode function RPC处理器返回的错误码
---@field ErrorMessage function RPC处理器返回的错误信息
local IRPCStatus = {}