---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yongzyzhang.
--- DateTime: 2024/4/17 下午4:05
---

local M = {}

--TSF4G服务名
M.NameOfGidServer = "GidService"
M.NameOfLobbyServer = "LobbyService"
M.NameOfWorldManagerServer = "WorldProxyService"
M.NameOfOfficeServer = "OfficeService"
M.NameOfAgentServer = "AgentService"

--TSF4G服务上绑定的RPCService名
M.GidRPCServiceName = "HiGame.GidService"
M.LobbyRPCServiceName = "HiGame.Lobby"
M.WorldProxyRPCService = "HiGame.WorldProxyManager"
M.OfficeRPCServiceName = "HiGame.Office.MSOfficeService"
M.AgentRPCServiceName = "HiGame.AgentService"
M.OfficeDesignShareServiceName = "HiGame.Office.OfficeDesignShareService"


M.Proto2MicroServiceNameMap = {
    [M.GidRPCServiceName] = {
        ProtoFile = "Services/GidService.proto", TSF4G2ServerName=M.NameOfGidServer, Stateful = false
    },
    [M.LobbyRPCServiceName] = {
        ProtoFile = "Services/LobbyService.proto", TSF4G2ServerName=M.NameOfLobbyServer, Stateful = true
    },
    [M.WorldProxyRPCService] = {
        ProtoFile = "Services/WorldProxyService.proto", TSF4G2ServerName=M.NameOfWorldManagerServer, Stateful = true
    },
    [M.OfficeRPCServiceName] = {
        ProtoFile = "Services/OfficeService/office_ms.proto", TSF4G2ServerName=M.NameOfOfficeServer, Stateful = true
    },
    [M.AgentRPCServiceName] = {
        ProtoFile = "Services/AgentService.proto", TSF4G2ServerName=M.NameOfAgentServer, Stateful = true
    },
    [M.OfficeDesignShareServiceName] = {
        ProtoFile = "Services/OfficeService/OfficeDesignShareService.proto", TSF4G2ServerName=M.NameOfOfficeServer, Stateful = true
    },
}

--TSF4G2 服务上的Avatar Entity绑定的服务名
M.AvatarEntityMetaName = "HiGame.AvatarProxyInterface"
--TSF4G2 服务上的Office Entity绑定的服务名
M.MSOfficeEntityMetaName = "HiGame.Office.MSOfficeEntity"

M.EntityMeta2ProtoFileMap = {
    [M.AvatarEntityMetaName] = "Entities/AvatarProxy.proto";
    [M.MSOfficeEntityMetaName] = "Services/OfficeService/office_ms_entity.proto";
}

return M
