---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yongzyzhang.
--- DateTime: 2024/6/17 下午9:46
---

local G = require("G")
local ComponentBase = require("common.componentbase")
local Component = require("common.component")
local GameEventBus = require("common.GameEventBus")
local MsConfig = require("micro_service.ms_config")
---@class HeroCharacterComponent
---@field LocalHeroCharacterCache TMap 不同步，客户端和DS分别自行Cache
local HeroCharacterComponent = Component(ComponentBase)
local decorator = HeroCharacterComponent.decorator

function HeroCharacterComponent:ReceiveBeginPlay()
    Super(HeroCharacterComponent).ReceiveBeginPlay(self)
    if (not UE.UHiUtilsFunctionLibrary.IsLocalAdapter()) and UE.UHiUtilsFunctionLibrary.IsClient(self) then
        local IRPC = require("micro_service.irpc.irpc")
        local Protoc = require("micro_service.ProtocInstance")
        Protoc:loadfile("Services/HeroCharacterService.proto")
        IRPC:BindRPCService("HiGame.ClientHeroCharacterInterface", self)
    end
    
    self.AvatarEntityInvoker = self:GetOwner():GetRemoteMetaInvoker(MsConfig.AvatarEntityMetaName, self:GetOwner():GetPlayerRoleId())
end 

function HeroCharacterComponent:ReceiveEndPlay()
    Super(HeroCharacterComponent).ReceiveEndPlay(self)
end

decorator.entity_service_handler()
function HeroCharacterComponent:NotifyDSHeroData(ServerCtx, Request)
    G.log:info("HeroCharacter", "HeroCharacterComponent:NotifyDSHeroData")

    self:OnNotifyHeroes(Request.HeroMap)
end


function HeroCharacterComponent:NotifyClientHeroData(ServerCtx, Request)
    G.log:info("HeroCharacter", "HeroCharacterComponent:NotifyClientHeroData")
    self:OnNotifyHeroes(Request.HeroMap)
end

function HeroCharacterComponent:OnNotifyHeroes(HeroMap)
    for HeroID, HeroData in pairs(HeroMap) do
        self.LocalHeroCharacterCache:Add(HeroID, HeroData)
    end
    GameEventBus.GetEventBusInstance(self):BroadCastEvent(GameEventBus.EventType.OnNotifyPlayerHeroCharacter, self.LocalHeroCharacterCache)
end

decorator.message_receiver()
function HeroCharacterComponent:GmAddHero(HeroID)
    local Req = {
        HeroID = HeroID,
    }
    self.AvatarEntityInvoker:GMAddHero(Req)
end


decorator.message_receiver()
function HeroCharacterComponent:GmAddHeroExp(HeroID, Exp)
    local Req = {
        HeroID = HeroID,
        AddExpNum = Exp
    }
    self.AvatarEntityInvoker:GMAddHeroExp(Req)
end

return HeroCharacterComponent