---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuw.
--- DateTime: 2023/11/17 10:05
---

local SlotSave = {}

---@return UClass
local function SaveGameClass()
    return LoadClass("/Game/Developers/CP0032305_GH/Dev/BP_HiSaveGame.BP_HiSaveGame_C")
end
---@param SlotName string
---@return BP_HiSaveGame_C
SlotSave.GetSlot = function(SlotName)
    ---@type BP_HiSaveGame_C
    local SaveGame = UE.UGameplayStatics.LoadGameFromSlot(SlotName, 0)
    if not SaveGame then
        SaveGame = UE.UGameplayStatics.CreateSaveGameObject(SaveGameClass())
        SaveGame.SlotName = SlotName
    end
    return SaveGame
end

---@param FileName string
---@return string
SlotSave.ReadContentFile = function(FileName)
    return SlotSave.ReadFile(UE.UBlueprintPathsLibrary.ProjectContentDir() .. "/" .. FileName)
end

---@param File string
---@return string
SlotSave.ReadFile = function(FileName)
    local File = UE.File()
    if not File:Open(FileName, "r") then
        print("SlotSave.ReadFile err " .. File)
        return ""
    end
    local Content = File:Read("a")
    File:Close()
    return Content
end

---@param FileName string
---@param Content string
---@return integer
SlotSave.WriteFile = function(FileName, Content)
    local File = UE.File()
    if not File:Open(FileName, "w+") then
        print("SlotSave.WriteFile err " .. FileName)
        return ""
    end
    local Num = File:Write(Content)
    File:Close()
    return Num
end

return SlotSave