-------------------------------------------------------------------------------
--- @copyright Copyright (c) 2024 Tencent Inc. All rights reserved.
--- @brief allSongOutputFile.xlsx/OzValley - Flute_sheet
--- 注意：本文件由导表程序自动生成，严禁手动修改！所有修改内容均会在下次导表时被覆盖！
-------------------------------------------------------------------------------
local M = {}

M.data = {
    [1] = {
        minDuration = 200,
        perfectTime = 6490,
        keyPosition = 2,
        keyType = 1,
        duration = 6,
    },
    [2] = {
        minDuration = 200,
        perfectTime = 12970,
        keyPosition = 1,
        keyType = 1,
        duration = 6,
    },
    [3] = {
        minDuration = 200,
        perfectTime = 17840,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [4] = {
        minDuration = 200,
        perfectTime = 25950,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [5] = {
        minDuration = 200,
        perfectTime = 32430,
        keyPosition = 4,
        keyType = 1,
        duration = 4,
    },
    [6] = {
        minDuration = 200,
        perfectTime = 33240,
        keyPosition = 5,
        keyType = 1,
        duration = 6,
    },
    [7] = {
        minDuration = 200,
        perfectTime = 35680,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [8] = {
        minDuration = 200,
        perfectTime = 36490,
        keyPosition = 2,
        keyType = 1,
        duration = 6,
    },
    [9] = {
        minDuration = 200,
        perfectTime = 38110,
        keyPosition = 6,
        keyType = 1,
        duration = 4,
    },
    [10] = {
        minDuration = 200,
        perfectTime = 38920,
        keyPosition = 6,
        keyType = 1,
        duration = 2,
    },
    [11] = {
        minDuration = 200,
        perfectTime = 39320,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [12] = {
        minDuration = 200,
        perfectTime = 39530,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [13] = {
        minDuration = 200,
        perfectTime = 39730,
        keyPosition = 6,
        keyType = 1,
        duration = 2,
    },
    [14] = {
        minDuration = 200,
        perfectTime = 40140,
        keyPosition = 5,
        keyType = 1,
        duration = 6,
    },
    [15] = {
        minDuration = 200,
        perfectTime = 41760,
        keyPosition = 6,
        keyType = 1,
        duration = 2,
    },
    [16] = {
        minDuration = 200,
        perfectTime = 42160,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [17] = {
        minDuration = 200,
        perfectTime = 45410,
        keyPosition = 2,
        keyType = 1,
        duration = 4,
    },
    [18] = {
        minDuration = 200,
        perfectTime = 46220,
        keyPosition = 1,
        keyType = 1,
        duration = 6,
    },
    [19] = {
        minDuration = 200,
        perfectTime = 48650,
        keyPosition = 2,
        keyType = 1,
        duration = 4,
    },
    [20] = {
        minDuration = 200,
        perfectTime = 49460,
        keyPosition = 1,
        keyType = 1,
        duration = 6,
    },
    [21] = {
        minDuration = 200,
        perfectTime = 51080,
        keyPosition = 5,
        keyType = 1,
        duration = 4,
    },
    [22] = {
        minDuration = 200,
        perfectTime = 51890,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [23] = {
        minDuration = 200,
        perfectTime = 52090,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [24] = {
        minDuration = 200,
        perfectTime = 52300,
        keyPosition = 5,
        keyType = 1,
        duration = 6,
    },
    [25] = {
        minDuration = 200,
        perfectTime = 54320,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [26] = {
        minDuration = 200,
        perfectTime = 55140,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [27] = {
        minDuration = 200,
        perfectTime = 58380,
        keyPosition = 6,
        keyType = 1,
        duration = 6,
    },
    [28] = {
        minDuration = 200,
        perfectTime = 61620,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [29] = {
        minDuration = 200,
        perfectTime = 63240,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [30] = {
        minDuration = 200,
        perfectTime = 64860,
        keyPosition = 2,
        keyType = 1,
        duration = 6,
    },
    [31] = {
        minDuration = 200,
        perfectTime = 66490,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [32] = {
        minDuration = 200,
        perfectTime = 68110,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [33] = {
        minDuration = 200,
        perfectTime = 69730,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [34] = {
        minDuration = 200,
        perfectTime = 71350,
        keyPosition = 3,
        keyType = 1,
        duration = 6,
    },
    [35] = {
        minDuration = 200,
        perfectTime = 94860,
        keyPosition = 4,
        keyType = 1,
        duration = 4,
    },
    [36] = {
        minDuration = 200,
        perfectTime = 95680,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [37] = {
        minDuration = 200,
        perfectTime = 96490,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [38] = {
        minDuration = 200,
        perfectTime = 97300,
        keyPosition = 6,
        keyType = 1,
        duration = 6,
    },
    [39] = {
        minDuration = 200,
        perfectTime = 98920,
        keyPosition = 1,
        keyType = 1,
        duration = 6,
    },
    [40] = {
        minDuration = 200,
        perfectTime = 111080,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [41] = {
        minDuration = 200,
        perfectTime = 114320,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [42] = {
        minDuration = 200,
        perfectTime = 117770,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [43] = {
        minDuration = 200,
        perfectTime = 117970,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [44] = {
        minDuration = 200,
        perfectTime = 118180,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [45] = {
        minDuration = 200,
        perfectTime = 118380,
        keyPosition = 3,
        keyType = 1,
        duration = 4,
    },
    [46] = {
        minDuration = 200,
        perfectTime = 119190,
        keyPosition = 4,
        keyType = 1,
        duration = 4,
    },
    [47] = {
        minDuration = 200,
        perfectTime = 120000,
        keyPosition = 3,
        keyType = 1,
        duration = 6,
    },
    [48] = {
        minDuration = 200,
        perfectTime = 123240,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [49] = {
        minDuration = 200,
        perfectTime = 123450,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [50] = {
        minDuration = 200,
        perfectTime = 123650,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [51] = {
        minDuration = 200,
        perfectTime = 123850,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [52] = {
        minDuration = 200,
        perfectTime = 124050,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [53] = {
        minDuration = 200,
        perfectTime = 124260,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [54] = {
        minDuration = 200,
        perfectTime = 124460,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [55] = {
        minDuration = 200,
        perfectTime = 124660,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [56] = {
        minDuration = 200,
        perfectTime = 124860,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [57] = {
        minDuration = 200,
        perfectTime = 125070,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [58] = {
        minDuration = 200,
        perfectTime = 125270,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [59] = {
        minDuration = 200,
        perfectTime = 125470,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [60] = {
        minDuration = 200,
        perfectTime = 125680,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [61] = {
        minDuration = 200,
        perfectTime = 125880,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [62] = {
        minDuration = 200,
        perfectTime = 126080,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [63] = {
        minDuration = 200,
        perfectTime = 126280,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [64] = {
        minDuration = 200,
        perfectTime = 127300,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [65] = {
        minDuration = 200,
        perfectTime = 127500,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [66] = {
        minDuration = 200,
        perfectTime = 127700,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [67] = {
        minDuration = 200,
        perfectTime = 127910,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [68] = {
        minDuration = 200,
        perfectTime = 128110,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [69] = {
        minDuration = 200,
        perfectTime = 128310,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [70] = {
        minDuration = 200,
        perfectTime = 128510,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [71] = {
        minDuration = 200,
        perfectTime = 128720,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [72] = {
        minDuration = 200,
        perfectTime = 128920,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [73] = {
        minDuration = 200,
        perfectTime = 129120,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [74] = {
        minDuration = 200,
        perfectTime = 129320,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [75] = {
        minDuration = 200,
        perfectTime = 129530,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [76] = {
        minDuration = 200,
        perfectTime = 130540,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [77] = {
        minDuration = 200,
        perfectTime = 130740,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [78] = {
        minDuration = 200,
        perfectTime = 130950,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [79] = {
        minDuration = 200,
        perfectTime = 131150,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [80] = {
        minDuration = 200,
        perfectTime = 131350,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [81] = {
        minDuration = 200,
        perfectTime = 131550,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [82] = {
        minDuration = 200,
        perfectTime = 131760,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [83] = {
        minDuration = 200,
        perfectTime = 131960,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [84] = {
        minDuration = 200,
        perfectTime = 132160,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [85] = {
        minDuration = 200,
        perfectTime = 132360,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [86] = {
        minDuration = 200,
        perfectTime = 132570,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [87] = {
        minDuration = 200,
        perfectTime = 132770,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [88] = {
        minDuration = 200,
        perfectTime = 133380,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [89] = {
        minDuration = 200,
        perfectTime = 133580,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [90] = {
        minDuration = 200,
        perfectTime = 133780,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [91] = {
        minDuration = 200,
        perfectTime = 133990,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [92] = {
        minDuration = 200,
        perfectTime = 134190,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [93] = {
        minDuration = 200,
        perfectTime = 134390,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [94] = {
        minDuration = 200,
        perfectTime = 134590,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [95] = {
        minDuration = 200,
        perfectTime = 134800,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [96] = {
        minDuration = 200,
        perfectTime = 135000,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [97] = {
        minDuration = 200,
        perfectTime = 135200,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [98] = {
        minDuration = 200,
        perfectTime = 135410,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [99] = {
        minDuration = 200,
        perfectTime = 135610,
        keyPosition = 6,
        keyType = 2,
        duration = 1,
    },
    [100] = {
        minDuration = 200,
        perfectTime = 135810,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [101] = {
        minDuration = 200,
        perfectTime = 136010,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [102] = {
        minDuration = 200,
        perfectTime = 136220,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [103] = {
        minDuration = 200,
        perfectTime = 137030,
        keyPosition = 2,
        keyType = 1,
        duration = 6,
    },
    [104] = {
        minDuration = 200,
        perfectTime = 139460,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [105] = {
        minDuration = 200,
        perfectTime = 140270,
        keyPosition = 3,
        keyType = 1,
        duration = 6,
    },
    [106] = {
        minDuration = 200,
        perfectTime = 141890,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [107] = {
        minDuration = 200,
        perfectTime = 142700,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [108] = {
        minDuration = 200,
        perfectTime = 143110,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [109] = {
        minDuration = 200,
        perfectTime = 143310,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [110] = {
        minDuration = 200,
        perfectTime = 143510,
        keyPosition = 6,
        keyType = 1,
        duration = 2,
    },
    [111] = {
        minDuration = 200,
        perfectTime = 143920,
        keyPosition = 1,
        keyType = 1,
        duration = 6,
    },
    [112] = {
        minDuration = 200,
        perfectTime = 149190,
        keyPosition = 4,
        keyType = 1,
        duration = 4,
    },
    [113] = {
        minDuration = 200,
        perfectTime = 150000,
        keyPosition = 3,
        keyType = 1,
        duration = 6,
    },
    [114] = {
        minDuration = 200,
        perfectTime = 152430,
        keyPosition = 3,
        keyType = 1,
        duration = 4,
    },
    [115] = {
        minDuration = 200,
        perfectTime = 153240,
        keyPosition = 5,
        keyType = 1,
        duration = 6,
    },
    [116] = {
        minDuration = 200,
        perfectTime = 154860,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [117] = {
        minDuration = 200,
        perfectTime = 155680,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [118] = {
        minDuration = 200,
        perfectTime = 155880,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [119] = {
        minDuration = 200,
        perfectTime = 156080,
        keyPosition = 5,
        keyType = 1,
        duration = 6,
    },
}

M.extra_data = {}

return M
