-------------------------------------------------------------------------------
--- @copyright Copyright (c) 2024 Tencent Inc. All rights reserved.
--- @brief allSongOutputFile.xlsx/test_sheet
--- 注意：本文件由导表程序自动生成，严禁手动修改！所有修改内容均会在下次导表时被覆盖！
-------------------------------------------------------------------------------
local M = {}

M.data = {
    [1] = {
        minDuration = 280,
        perfectTime = 1250,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [2] = {
        minDuration = 280,
        perfectTime = 1560,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [3] = {
        minDuration = 280,
        perfectTime = 1880,
        keyPosition = 5,
        keyType = 1,
        duration = 2,
    },
    [4] = {
        minDuration = 280,
        perfectTime = 2500,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [5] = {
        minDuration = 280,
        perfectTime = 3120,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [6] = {
        minDuration = 280,
        perfectTime = 3750,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [7] = {
        minDuration = 280,
        perfectTime = 5000,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [8] = {
        minDuration = 280,
        perfectTime = 5310,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [9] = {
        minDuration = 280,
        perfectTime = 5620,
        keyPosition = 3,
        keyType = 1,
        duration = 2,
    },
    [10] = {
        minDuration = 280,
        perfectTime = 6250,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [11] = {
        minDuration = 280,
        perfectTime = 6880,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [12] = {
        minDuration = 280,
        perfectTime = 7500,
        keyPosition = 5,
        keyType = 1,
        duration = 4,
    },
    [13] = {
        minDuration = 280,
        perfectTime = 8750,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [14] = {
        minDuration = 280,
        perfectTime = 9060,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [15] = {
        minDuration = 280,
        perfectTime = 9380,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [16] = {
        minDuration = 280,
        perfectTime = 10000,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [17] = {
        minDuration = 280,
        perfectTime = 10620,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [18] = {
        minDuration = 280,
        perfectTime = 11250,
        keyPosition = 5,
        keyType = 1,
        duration = 2,
    },
    [19] = {
        minDuration = 280,
        perfectTime = 11880,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [20] = {
        minDuration = 280,
        perfectTime = 12500,
        keyPosition = 5,
        keyType = 2,
        duration = 1,
    },
    [21] = {
        minDuration = 280,
        perfectTime = 12810,
        keyPosition = 4,
        keyType = 2,
        duration = 1,
    },
    [22] = {
        minDuration = 280,
        perfectTime = 13120,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [23] = {
        minDuration = 280,
        perfectTime = 13750,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [24] = {
        minDuration = 280,
        perfectTime = 14380,
        keyPosition = 5,
        keyType = 1,
        duration = 2,
    },
    [25] = {
        minDuration = 280,
        perfectTime = 15000,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [26] = {
        minDuration = 280,
        perfectTime = 18120,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [27] = {
        minDuration = 280,
        perfectTime = 18440,
        keyPosition = 3,
        keyType = 2,
        duration = 1,
    },
    [28] = {
        minDuration = 280,
        perfectTime = 18750,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [29] = {
        minDuration = 280,
        perfectTime = 19380,
        keyPosition = 5,
        keyType = 1,
        duration = 2,
    },
    [30] = {
        minDuration = 280,
        perfectTime = 20000,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [31] = {
        minDuration = 280,
        perfectTime = 20620,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [32] = {
        minDuration = 280,
        perfectTime = 21880,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [33] = {
        minDuration = 280,
        perfectTime = 22190,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [34] = {
        minDuration = 280,
        perfectTime = 22500,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [35] = {
        minDuration = 280,
        perfectTime = 23120,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [36] = {
        minDuration = 280,
        perfectTime = 23750,
        keyPosition = 4,
        keyType = 1,
        duration = 2,
    },
    [37] = {
        minDuration = 280,
        perfectTime = 24380,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
    [38] = {
        minDuration = 280,
        perfectTime = 25620,
        keyPosition = 1,
        keyType = 2,
        duration = 1,
    },
    [39] = {
        minDuration = 280,
        perfectTime = 25940,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [40] = {
        minDuration = 280,
        perfectTime = 26250,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [41] = {
        minDuration = 280,
        perfectTime = 26880,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [42] = {
        minDuration = 280,
        perfectTime = 27500,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [43] = {
        minDuration = 280,
        perfectTime = 28120,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [44] = {
        minDuration = 280,
        perfectTime = 28750,
        keyPosition = 4,
        keyType = 1,
        duration = 6,
    },
    [45] = {
        minDuration = 280,
        perfectTime = 31250,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [46] = {
        minDuration = 280,
        perfectTime = 31560,
        keyPosition = 2,
        keyType = 2,
        duration = 1,
    },
    [47] = {
        minDuration = 280,
        perfectTime = 31880,
        keyPosition = 5,
        keyType = 1,
        duration = 2,
    },
    [48] = {
        minDuration = 280,
        perfectTime = 32500,
        keyPosition = 2,
        keyType = 1,
        duration = 2,
    },
    [49] = {
        minDuration = 280,
        perfectTime = 33120,
        keyPosition = 1,
        keyType = 1,
        duration = 2,
    },
    [50] = {
        minDuration = 280,
        perfectTime = 33750,
        keyPosition = 1,
        keyType = 1,
        duration = 4,
    },
}

M.extra_data = {}

return M
