--- 通用的Proto文件的内存编译器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yongzyzhang.
--- DateTime: 2024/5/17 上午11:48
---
local G = require("G")

local PROTOC 
pcall(function() 
    PROTOC = require("micro_service.irpc.protoc").new()
end)

PROTOC:addpath(UE.UKismetSystemLibrary.GetProjectContentDirectory() .. "Protos/")
PROTOC:addpath(UE.UKismetSystemLibrary.GetProjectContentDirectory() .. "Protos/Thirdparty/")


-- 自动处理import依赖 @see https://github.com/starwing/lua-protobuf/blob/master/README.zh.md
PROTOC.include_imports = true
PROTOC.unknown_import = function(self, module_name)
    G.log:error("PROTOC unknown_import module_name:" .. module_name)
end

PROTOC.unknown_type = function(self, type_name)
    G.log:error("PROTOC unknown_type type_name:" .. type_name)
end

return PROTOC