---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by santihong.
--- DateTime: 2024/3/27 14:31
---

local _M = {}

_M.RelivePointTag = "RelivePoint"

-- Message events
local MsgCode = {}

MsgCode.OnFinishRelivePlayer = "OnFinishRelivePlayer"
MsgCode.ClearAllStates = "ClearAllStates"
MsgCode.ReliveAllPlayers = "ReliveAllPlayers"
MsgCode.OnRelive = "OnRelive"
MsgCode.ShowQTE = "ShowQTE"
MsgCode.EndQTE = "EndQTE"
MsgCode.TriggerQTE = "TriggerQTE"
MsgCode.AllPlayerDead = "AllPlayerDead"

_M.MsgCode = MsgCode

return _M
